"""Initial schema

Revision ID: c5324edbeac4
Revises: 
Create Date: 2026-09-30 20:49:50.006796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5324edbeac4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrower_external_id'), 'borrower', ['external_id'], unique=True)
    op.create_index(op.f('ix_borrower_id'), 'borrower', ['id'], unique=False)
    op.create_table('recovery_journey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_journey_id'), 'recovery_journey', ['id'], unique=False)
    op.create_table('borrower_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_index', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['recovery_journey.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journey_id', 'snapshot_index', name='uq_journey_snapshot')
    )
    op.create_index(op.f('ix_borrower_snapshot_id'), 'borrower_snapshot', ['id'], unique=False)
    op.create_table('recovery_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('solver_used', sa.String(), nullable=True),
    sa.Column('solver_version', sa.String(), nullable=True),
    sa.Column('constraint_registry_version', sa.String(), nullable=True),
    sa.Column('original_risk', sa.Float(), nullable=True),
    sa.Column('target_risk', sa.Float(), nullable=True),
    sa.Column('total_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['recovery_journey.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journey_id', 'plan_version', name='uq_journey_plan')
    )
    op.create_index(op.f('ix_recovery_plan_id'), 'recovery_plan', ['id'], unique=False)
    op.create_table('model_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('predicted_default_risk', sa.Float(), nullable=True),
    sa.Column('risk_band', sa.String(), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('recovery_applicable', sa.Boolean(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('feature_contract_version', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['recovery_journey.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['borrower_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_decision_id'), 'model_decision', ['id'], unique=False)
    op.create_table('recovery_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('feature_name', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('monthly_change', sa.Float(), nullable=True),
    sa.Column('cumulative_target', sa.Float(), nullable=True),
    sa.Column('reassessment_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['recovery_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_action_id'), 'recovery_action', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_action_id'), table_name='recovery_action')
    op.drop_table('recovery_action')
    op.drop_index(op.f('ix_model_decision_id'), table_name='model_decision')
    op.drop_table('model_decision')
    op.drop_index(op.f('ix_recovery_plan_id'), table_name='recovery_plan')
    op.drop_table('recovery_plan')
    op.drop_index(op.f('ix_borrower_snapshot_id'), table_name='borrower_snapshot')
    op.drop_table('borrower_snapshot')
    op.drop_index(op.f('ix_recovery_journey_id'), table_name='recovery_journey')
    op.drop_table('recovery_journey')
    op.drop_index(op.f('ix_borrower_id'), table_name='borrower')
    op.drop_index(op.f('ix_borrower_external_id'), table_name='borrower')
    op.drop_table('borrower')
    # ### end Alembic commands ###
